apiVersion: v1
kind: ConfigMap
metadata:
  name: url-shortener-config
  labels:
    app: url-shortener
data:
  DATABASE_URL: "postgresql://postgres:password@postgres-service:5432/url_shortener_db"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  APP_ENV: "production"
---
apiVersion: v1
kind: Secret
metadata:
  name: url-shortener-secrets
  labels:
    app: url-shortener
type: Opaque
data:
  # Base64 encoded values
  # postgres_password = "password" -> cGFzc3dvcmQ=
  # jwt_secret = "your-secret-key-here" -> eW91ci1zZWNyZXQta2V5LWhlcmU=
  postgres_password: cGFzc3dvcmQ=
  jwt_secret: eW91ci1zZWNyZXQta2V5LWhlcmU=