apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: url-shortener-app
  template:
    metadata:
      labels:
        app: url-shortener-app
    spec:
      containers:
      - name: web
        image: url-shortener-app
        imagePullPolicy: Never 
        ports:
        - containerPort: 8000
        # THIS SECTION IS THE FIX
        env:
        - name: DATABASE_URL
          value: "postgresql://postgres:password@kubernetes.docker.internal:5432/url_shortener_db"
